### ISSUE TITLE
Segementation fault using precompiled binary

### ISSUE THREAD

**Issue by jberkus** [sebasmonia/nordvpn-client#1]
[jberkus@fedora ~]$ nordvpn-client 
Segmentation fault (core dumped)

(no core file found)

● fedora:fedora/36/x86_64/silverblue
                  Version: 36.20230119.0 (2023-01-19T00:49:43Z)
               BaseCommit: 69e3c81e83c35969d2bdc6197cd42e29c21bc93f32a73f3b642051139d92fc45
          LayeredPackages: gstreamer1-plugin-openh264

Next steps?

**Comment by sebasmonia** [comment]
Hi @jberkus!!! first time I see this error, from reading a bit about it seems that the SBCL core can't be found, yet the executable is supposed to be standalone and not have any dependencies. For example, I can run it outside the development Toolbox, where `sbcl` is not installed.  
I generated a new, fresh executable from an updated Toolbox and using a slightly different setup that I found in the Common Lisp cookbook.  

Let me know how it goes after giving it a try. In the meantime I will keep looking to repro in my local.  
Thank you!

**Comment by jberkus** [comment]
Feh, still getting a core dump with no core.  I'm tinkering with system settings to see if there's something preventing the core file from being created.

**Comment by sebasmonia** [comment]
Hey there, sorry for the delay, had crazy week.

I did try a few more things but no luck. I don't have another Silverblue system to test but there's a Workstation laptop where it ran OK.
Did you find something in your system?

**Comment by sebasmonia** [comment]
Will close this, but feel free to reopen if you have any updates.
